version: '3.8'
services:
  nginx:
    image: nginx:alpine
    links:
      - env:env
      - node:node
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${LOCAL_PORT}:80
  node:
    image: "node:alpine"
    working_dir: /opt/front
    volumes:
      - ./front:/opt/front
      - /opt/front/node_modules
    entrypoint: "/bin/sh -c 'yarn install && yarn run dev'"

  env:
    image: "node:alpine"
    environment:
      - DATASTORE_EMULATOR_HOST=datastore:8059
      - DATASTORE_PROJECT_ID=node-datastore-test-111
      - PORT=8080
      - APP_URL=http://localhost:${LOCAL_PORT}
    working_dir: /opt/app
    volumes:
      - ./server:/opt/app
    links:
      - datastore:datastore
    command: /bin/sh -c 'yarn install && yarn run start'
  datastore:
    image: google/cloud-sdk
    environment:
      - PROJECT_ID=node-datastore-test-111
    command: /bin/bash -c "gcloud beta emulators datastore start --host-port 0.0.0.0:8059 --project $$PROJECT_ID --data-dir /data"
    ports:
      - 8059:8059
    volumes:
      - datastore_volume:/data
volumes:
  datastore_volume: